# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/sources.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
src/array/mulle--array.c
src/array/mulle-array.c
src/array/pointer/mulle--pointerarray.c
src/array/pointer/mulle-pointerarray.c
src/array/struct/mulle--structarray.c
src/array/struct/mulle-structarray.c
src/array/uniquepointer/mulle--uniquepointerarray.c
src/array/uniquepointer/mulle-uniquepointerarray.c
src/assoc/mulle--assoc.c
src/assoc/mulle-assoc.c
src/assoc/pointerpair/mulle--pointerpairarray.c
src/assoc/pointerpair/mulle-pointerpairarray.c
src/assoc/pointerpair/mulle-pointerpair.c
src/map/mulle--map.c
src/map/mulle-map.c
src/map/pointer/mulle--pointermap-generic.c
src/map/pointer/mulle--pointermap-struct.c
src/mulle-container-callback.c
src/mulle-qsort.c
src/queue/mulle--pointerqueue.c
src/queue/mulle-pointerqueue.c
src/queue/struct/mulle--structqueue.c
src/queue/struct/mulle-structqueue.c
src/rangeset/mulle--rangeset.c
src/set/mulle--set.c
src/set/mulle-set.c
src/set/pointer/mulle--pointerset-generic.c
src/set/pointer/mulle--pointerset-struct.c
)
