//
//  include.h
//  mulle-container
//
//  Copyright (c) 2022 Nat! - Mulle kybernetiK.
//  All rights reserved.
//
//
//  Redistribution and use in source and binary forms, with or without
//  modification, are permitted provided that the following conditions are met:
//
//  Redistributions of source code must retain the above copyright notice, this
//  list of conditions and the following disclaimer.
//
//  Redistributions in binary form must reproduce the above copyright notice,
//  this list of conditions and the following disclaimer in the documentation
//  and/or other materials provided with the distribution.
//
//  Neither the name of Mulle kybernetiK nor the names of its contributors
//  may be used to endorse or promote products derived from this software
//  without specific prior written permission.
//
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
//  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
//  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
//  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
//  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
//  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
//  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
//  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
//  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
//  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
//  POSSIBILITY OF SUCH DAMAGE.
//
#ifndef mulle_container_include_h__
#define mulle_container_include_h__

/* This is a central include file to keep dependencies out of the library
   C files. It is usally included by .h files only.

   The advantage is that now .c and .h files become motile. They can
   be moved to other projects and don't need to be edited. Also less typing...

   Therefore it is important that this file is called "include.h" and
   not "mulle-container-include.h" to keep the #include statements in the
   library code uniform.

   The C-compiler will pick up the nearest one.
*/

/* Include the header file automatically generated by c-sourcetree-update.
   Here the prefix is harmless and serves disambiguation. If you have no
   sourcetree, then you don't need it.
 */

// if compiling with NDEBUG, we don't do the asserts so we can leave it out.
// this is painful, when you mix different libraries though that are compiled
// differently. So we keep the fields in the actual structs constants but
// unused unless you define MULLE__CONTAINER_MISER_MODE
//
#ifndef MULLE__CONTAINER_HAVE_MUTATION_COUNT
# ifdef NDEBUG
#  define MULLE__CONTAINER_HAVE_MUTATION_COUNT  0
# else
#  define MULLE__CONTAINER_HAVE_MUTATION_COUNT  1
# endif
#endif

#if ! MULLE__CONTAINER_HAVE_MUTATION_COUNT || defined( NDEBUG)
# define MULLE__CONTAINER_MUTATION_NDEBUG
#endif

#if MULLE__CONTAINER_HAVE_MUTATION_COUNT && defined( MULLE__CONTAINER_MISER_MODE)
# error "You can't define MULLE__CONTAINER_MISER_MODE and also have MULLE__CONTAINER_HAVE_MUTATION_COUNT enabled"
#endif


#include "_mulle-container-include.h"

#if defined( MULLE__CONTAINER_BUILD) || defined( MULLE__CORE_BUILD)
# define MULLE__CONTAINER_GLOBAL        MULLE_C_GLOBAL
# define MULLE__CONTAINER_GLOBAL_VAR    MULLE_C_GLOBAL_VAR
#else
# if defined( MULLE_CONTAINER_INCLUDE_DYNAMIC) || (defined( MULLE_INCLUDE_DYNAMIC) && ! defined( MULLE_CONTAINER_INCLUDE_STATIC))
#  define MULLE__CONTAINER_GLOBAL       MULLE_C_EXTERN_GLOBAL
# else
#  define MULLE__CONTAINER_GLOBAL       extern
# endif
# define MULLE__CONTAINER_GLOBAL_VAR
#endif




/* You can add some more include statements here */

#endif
