/*
 *   This file will be regenerated by `mulle-project-dependency-versions`.
 *   Any edits will be lost.
 */
#if defined( MULLE_ALLOCATOR_VERSION) && \
     MULLE_ALLOCATOR_VERSION < ((4 << 20) | (2 << 8) | 2)
# error "mulle-allocator is too old"
#endif
#if defined( MULLE_DATA_VERSION) && \
     MULLE_DATA_VERSION < ((0 << 20) | (0 << 8) | 1)
# error "mulle-data is too old"
#endif
