# cmake/_Dependencies.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

if( NOT MULLE_ALLOCATOR_LIBRARY)
   find_library( MULLE_ALLOCATOR_LIBRARY NAMES mulle-allocator)
   message( STATUS "MULLE_ALLOCATOR_LIBRARY is ${MULLE_ALLOCATOR_LIBRARY}")
   set( DEPENDENCY_LIBRARIES
      ${MULLE_ALLOCATOR_LIBRARY}
      ${DEPENDENCY_LIBRARIES}
      CACHE INTERNAL "need to cache this"
   )
   if( MULLE_ALLOCATOR_LIBRARY)
      # temporarily expand CMAKE_MODULE_PATH
      get_filename_component( TMP_MULLE_ALLOCATOR_ROOT "${MULLE_ALLOCATOR_LIBRARY}" DIRECTORY)
      get_filename_component( TMP_MULLE_ALLOCATOR_ROOT "${TMP_MULLE_ALLOCATOR_ROOT}" DIRECTORY)
      set( MEMO_CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH}")
      list( INSERT CMAKE_MODULE_PATH 0 "${TMP_MULLE_ALLOCATOR_ROOT}/include/cmake")
      # use explicit path to avoid "surprises"
      unset( MULLE_ALLOCATOR_DEFINITIONS)
      include( "${TMP_MULLE_ALLOCATOR_ROOT}/include/cmake/DependenciesAndLibraries.cmake" OPTIONAL)
      set( CMAKE_MODULE_PATH "${MEMO_CMAKE_MODULE_PATH}")

      set( INHERITED_DEFINITIONS
           ${MULLE_ALLOCATOR_DEFINITIONS}
           ${INHERITED_DEFINITIONS}
      )
  endif()
endif()

if( NOT CITYHASH_LIBRARY)
   find_library( CITYHASH_LIBRARY NAMES cityhash)
   message( STATUS "CITYHASH_LIBRARY is ${CITYHASH_LIBRARY}")
   set( DEPENDENCY_LIBRARIES
      ${CITYHASH_LIBRARY}
      ${DEPENDENCY_LIBRARIES}
      CACHE INTERNAL "need to cache this"
   )
   if( CITYHASH_LIBRARY)
      # temporarily expand CMAKE_MODULE_PATH
      get_filename_component( TMP_CITYHASH_ROOT "${CITYHASH_LIBRARY}" DIRECTORY)
      get_filename_component( TMP_CITYHASH_ROOT "${TMP_CITYHASH_ROOT}" DIRECTORY)
      set( MEMO_CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH}")
      list( INSERT CMAKE_MODULE_PATH 0 "${TMP_CITYHASH_ROOT}/include/cmake")
      # use explicit path to avoid "surprises"
      unset( CITYHASH_DEFINITIONS)
      include( "${TMP_CITYHASH_ROOT}/include/cmake/DependenciesAndLibraries.cmake" OPTIONAL)
      set( CMAKE_MODULE_PATH "${MEMO_CMAKE_MODULE_PATH}")

      set( INHERITED_DEFINITIONS
           ${CITYHASH_DEFINITIONS}
           ${INHERITED_DEFINITIONS}
      )
  endif()
endif()
