#
# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/array/_mulle-array.c
src/array/mulle-array.c
src/array/mulle-pointerarray.c
src/array/mulle-pointerpairarray.c
src/farmhash/farmhash.c
src/hash/mulle-hash.c
src/hash/mulle-prime.c
src/map/_mulle-bigmap.c
src/map/mulle-bigmap.c
src/map/_mulle-map.c
src/map/mulle-map.c
src/mulle-container-callback.c
src/queue/_mulle-queue.c
src/set/_mulle-bigset.c
src/set/mulle-bigset.c
src/set/mulle-pointerset.c
src/set/_mulle-set.c
src/set/mulle-set.c
)

set( STANDALONE_SOURCES
src/mulle-container-standalone.c
)
